public class ExemploExcecaoSimples
  public static void main(String[] args) { 
    int numerador = 10;
    int denominador = 0; // Causa uma exceção de divisão por zero
    
    try {
      // Código que pode lançar uma exceção
      int resultado = numerador / denominador;
      System.out.println("Resultado: " + resultado);
    } catch (ArithmeticException erroAritmetico) {
      // Código para tratar a exceção
      System.out.println("Erro tentativa de divisão por zero.");
  System.out.println("Detalhes do erro:" + Aritmetico.getMessage());
    } finally {
      // Código que sempre será executado, independentemente de uma exceção ter sido lançada ou não
      System.out.println("Bloco finally executado.");
    }
    System.out.println("O programa continua sua execução após o tratamento da exeção.");
  }
